apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        environment:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: vasu
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: adminpassword
        - name: MONGO_INITDB_DATABASE
          value: techdome-db
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
